# Merge --> Lecture 29

In [3]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [5]:
dframe1 = DataFrame({"key":['X','Z','Y','Z','X','X'], 'data_set_1':np.arange(6)})
dframe1

data_set_1 key
0           0   X
1           1   Z
2           2   Y
3           3   Z
4           4   X
5           5   X

In [6]:
dframe2 = DataFrame({"key":['Q', 'Y', 'Z'], 'data_set_2':[1,2,3]})
dframe2

data_set_2 key
0           1   Q
1           2   Y
2           3   Z

In [13]:
pd.merge(dframe1,dframe2, on= 'key')

data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2

In [12]:
pd.merge(dframe1,dframe2, on='key', how = 'left')
#left join

data_set_1 key  data_set_2
0           0   X         NaN
1           1   Z         3.0
2           2   Y         2.0
3           3   Z         3.0
4           4   X         NaN
5           5   X         NaN

In [16]:
pd.merge(dframe1,dframe2, on='key', how = 'right')
#right join

data_set_1 key  data_set_2
0         1.0   Z           3
1         3.0   Z           3
2         2.0   Y           2
3         NaN   Q           1

In [18]:
pd.merge(dframe1,dframe2, on='key', how = 'outer')
#outer join

data_set_1 key  data_set_2
0         0.0   X         NaN
1         4.0   X         NaN
2         5.0   X         NaN
3         1.0   Z         3.0
4         3.0   Z         3.0
5         2.0   Y         2.0
6         NaN   Q         1.0

In [21]:
dframe3 = DataFrame({'key':['X','X','X','Y','Z','Z'], 'data_set_3':range(6)})
dframe3
dframe4 = DataFrame({'key':['Y','Y','X','X','Z'], 'data_set_4':range(5)})
dframe4

data_set_4 key
0           0   Y
1           1   Y
2           2   X
3           3   X
4           4   Z

In [22]:
pd.merge(dframe3, dframe4)

data_set_3 key  data_set_4
0           0   X           2
1           0   X           3
2           1   X           2
3           1   X           3
4           2   X           2
5           2   X           3
6           3   Y           0
7           3   Y           1
8           4   Z           4
9           5   Z           4

In [30]:
df_left = DataFrame({'key1':['SF','SF','LA' ],
                    'key2': ['one', 'two', 'one'],
                    'left_data':[10,20,30]})
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [31]:
df_right = DataFrame({'key1':['SF','SF', 'LA', 'LA'],
                     'key2': ['one', 'one', 'one', 'two'],
                     'right_data':[40,50,60,70]})
df_right

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [32]:
pd.merge(df_left, df_right, on = ['key1','key2'], how = 'outer')

key1 key2  left_data  right_data
0   SF  one       10.0        40.0
1   SF  one       10.0        50.0
2   SF  two       20.0         NaN
3   LA  one       30.0        60.0
4   LA  two        NaN        70.0

In [33]:
# if we merge on only one key python adds suffix to second key 
pd.merge(df_left, df_right, on = 'key1', how = 'outer')
#key2_x is for left and y for right 

key1 key2_x  left_data key2_y  right_data
0   SF    one         10    one          40
1   SF    one         10    one          50
2   SF    two         20    one          40
3   SF    two         20    one          50
4   LA    one         30    one          60
5   LA    one         30    two          70


# Merge on Index - lecture 30

import numpy as np
import pandas as pd
from pandas import SEries, DataFrame

In [3]:
df_left = DataFrame({'key': [ 'X', 'Y','Z', 'X', 'Y'],
                    'data': range(5)})

In [4]:
df_left

data key
0     0   X
1     1   Y
2     2   Z
3     3   X
4     4   Y

In [6]:
df_right = DataFrame({'group_data':[10,20]}, index=['X', 'Y'])
df_right

group_data
X          10
Y          20

In [10]:
df_left_hr = DataFrame({'key1':['SF','SF','SF', 'LA', 'LA'],
                       'key2':[10,20,30,20,30],
                       'data_set':np.arange(5.)})

In [11]:
df_left_hr

data_set key1  key2
0       0.0   SF    10
1       1.0   SF    20
2       2.0   SF    30
3       3.0   LA    20
4       4.0   LA    30

In [14]:
df_right_hr = DataFrame(np.arange(10).reshape(5,2),
index=[['LA','LA', 'SF', 'SF', 'SF'],[20,10,10,10,20]],
                       columns= ['col_1', 'col_2'])
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [15]:
df_left.join(df_right)

data key  group_data
0     0   X         NaN
1     1   Y         NaN
2     2   Z         NaN
3     3   X         NaN
4     4   Y         NaN

# Concatenate function --> lecture31

In [16]:
import numpy as no
import pandas as pd 
from pandas import Series, DataFrame 

In [17]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.concatenate([arr1, arr1], axis =1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [19]:
np.concatenate([arr1,arr1], axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
ser1 =Series([0,1,2], index = ['T', 'U', 'V'])
ser2 =Series([3,4], index= ['X', 'Y'])
ser1


T    0
U    1
V    2
dtype: int64

In [22]:
ser2

X    3
Y    4
dtype: int64

In [24]:
pd.concat([ser1, ser2], axis = 1)
# it concate and produces a dataframe 

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [25]:
pd.concat([ser1, ser2])
# series no null informations 

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [26]:
# hierarchy index by giving keys 
pd.concat([ser1, ser2], keys = ['cat1', 'cat2'])
#cat1 --> ser1 cat2 -->ser2

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [27]:
dframe1 = DataFrame(np.random.randn(4,3), columns=[' X', 'Y', 'Z'])

dframe2 = DataFrame(np.random.randn(3,3), columns=['Y', 'Q', 'X'])



In [28]:
dframe1

X         Y         Z
0  1.132867 -0.309631 -0.559033
1  0.087781 -1.727759 -0.293886
2  0.298650  1.391181 -1.406257
3  2.067990 -0.022129  0.485182

In [29]:
dframe2

Y         Q         X
0 -0.817104  0.758245  1.309392
1 -0.473989  0.344675 -0.110500
2 -0.618858  0.079236 -0.985722

In [30]:
pd.concat([dframe1, dframe2])

X         Q         X         Y         Z
0  1.132867       NaN       NaN -0.309631 -0.559033
1  0.087781       NaN       NaN -1.727759 -0.293886
2  0.298650       NaN       NaN  1.391181 -1.406257
3  2.067990       NaN       NaN -0.022129  0.485182
0       NaN  0.758245  1.309392 -0.817104       NaN
1       NaN  0.344675 -0.110500 -0.473989       NaN
2       NaN  0.079236 -0.985722 -0.618858       NaN

In [31]:
pd.concat([dframe1,dframe2], ignore_index= True )
# you want a continuous index 

X         Q         X         Y         Z
0  1.132867       NaN       NaN -0.309631 -0.559033
1  0.087781       NaN       NaN -1.727759 -0.293886
2  0.298650       NaN       NaN  1.391181 -1.406257
3  2.067990       NaN       NaN -0.022129  0.485182
4       NaN  0.758245  1.309392 -0.817104       NaN
5       NaN  0.344675 -0.110500 -0.473989       NaN
6       NaN  0.079236 -0.985722 -0.618858       NaN

# Combine DataFrame--> lecture 32

In [33]:
nan =np.nan

In [34]:
ser1 =Series([2, nan, 4, nan, 6, nan], 
            index= [ 'Q', 'R', 'S', 'T', 'U', 'V'])

In [35]:
ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [36]:
ser2 = Series(np.arange(len(ser1)), dtype=np.float64,
              index= [ 'Q', 'R', 'S', 'T', 'U', 'V'])
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [37]:
Series(np.where(pd.isnull(ser1), ser2, ser1), index = ser1.index)

# using the where command

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [38]:
# Short-cut function is combine_first, which will work same as above long function of where 

ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [39]:
dframe_odd = DataFrame({'X':[1.,nan,3.,nan],
                        'Y':[nan, 5.,nan,7.],
                        'Z':[nan,9.,nan,11.]})

In [40]:
dframe_even = DataFrame({'X': [2.,4.,nan,6.,8.],
                        'Y':[nan,10.,12.,14.,16.]})

In [41]:
dframe_odd

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [42]:
dframe_even

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [43]:
dframe_odd.combine_first(dframe_even)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN

# Reshaping --> lecture 33 

In [44]:
# stack and unstack 

In [46]:
dframe1 = DataFrame(np.arange(8).reshape(2,4),
                   index = pd.Index(['LA', 'SF'], name= 'City'),
                   columns =pd.Index(['A','B','C','D'], name='Letter'))
dframe1

Letter  A  B  C  D
City              
LA      0  1  2  3
SF      4  5  6  7

In [47]:
dframe_st = dframe1.stack()
dframe_st
# pivoting as now letters aon the left side and not on the head

City  Letter
LA    A         0
      B         1
      C         2
      D         3
SF    A         4
      B         5
      C         6
      D         7
dtype: int32

In [48]:
dframe_st.unstack()
# unstacking it again

Letter  A  B  C  D
City              
LA      0  1  2  3
SF      4  5  6  7

In [50]:
# we can unstack it by city as well
dframe_st.unstack('City')

City    LA  SF
Letter        
A        0   4
B        1   5
C        2   6
D        3   7

In [66]:
ser1 = Series([0,1,2], index=['Q','X','Y'])
ser2 = Series([4,5,6], index=['X','Y','Z'])

In [67]:
dframe = pd.concat([ser1, ser2], keys=['Alpha', 'Beta'])

In [61]:
dframe
# not a dataframe, its a series

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [68]:
dframe.unstack()
# null values appears in the dataframe 

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [69]:
# how get rid of null
dframe.unstack().stack()


Alpha  Q    0.0
       X    1.0
       Y    2.0
Beta   X    4.0
       Y    5.0
       Z    6.0
dtype: float64

In [71]:
dframe.stack(dropna = False)


AttributeError: 'Series' object has no attribute 'stack'

# Pivoting --> lecture 34

In [72]:
# dframe_piv = dframe.pivot('rows', 'columns', 'values')
# dframe_piv

# Duplicates in DataFrame --> lecture 35

In [78]:
dframe = DataFrame({'key1':['A']*2 + ['B']*3,
                   'key2':[2,2,2,3,3]})

In [74]:
dframe

key1  key2
0    A     2
1    A     2
2    B     3
3    B     3
4    B     3

In [79]:
dframe.duplicated()
# first is false because till now no A 2 but when we go to second A 2 we already so it shows true


0    False
1     True
2    False
3    False
4     True
dtype: bool

In [80]:
dframe.drop_duplicates()

key1  key2
0    A     2
2    B     2
3    B     3

In [81]:
# dropping from columns 
dframe.drop_duplicates(['key1'])
#now B with 3 was also dropped  

key1  key2
0    A     2
2    B     2

In [83]:
# dropping the first one if duplicate
dframe.drop_duplicates(['key1'], take_last=True)

C:\Users\Jai Katariya\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: the take_last=True keyword is deprecated, use keep='last' instead
  from ipykernel import kernelapp as app


key1  key2
1    A     2
4    B     3

# Mapping --> lecture 37

In [84]:
dframe = DataFrame({'city':['Alma','Brian Head', 'Fox Park'],
                   'altitude':[3158,3000,2762]})
dframe

altitude        city
0      3158        Alma
1      3000  Brian Head
2      2762    Fox Park

In [ ]:
state_map = {'Alma':'Colorada', 'Brian Head':'Utah', 'Fox Park':'Wyoming'}


In [90]:
state_map

{'Alma': 'Colorada', 'Brian Head': 'Utah', 'Fox Park': 'Wyoming'}

In [91]:
dframe['state'] = dframe['city'].map(state_map)
# making a new column and now mapping it 

In [92]:
dframe

altitude        city     state
0      3158        Alma  Colorada
1      3000  Brian Head      Utah
2      2762    Fox Park   Wyoming

# Replace --> Lecture 38

In [93]:
ser1 = Series([1,2,3,4,1,2,3,4])

In [94]:
ser1

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [95]:
ser1.replace(1,100)
#pass one value

0    100
1      2
2      3
3      4
4    100
5      2
6      3
7      4
dtype: int64

In [96]:
ser1.replace([1,4],[100,400])
# pass a list 

0    100
1      2
2      3
3    400
4    100
5      2
6      3
7    400
dtype: int64

In [98]:
ser1.replace({4:np.nan})
#pass dictionary for replacing

0    1.0
1    2.0
2    3.0
3    NaN
4    1.0
5    2.0
6    3.0
7    NaN
dtype: float64

In [99]:
# Rename Index --> lecture 38

In [101]:
dframe = DataFrame(np.arange(12).reshape(3,4),
                  index = ['NY','LA','SF'],
                  columns =['A','B','C','D'])
dframe

A  B   C   D
NY  0  1   2   3
LA  4  5   6   7
SF  8  9  10  11

In [103]:
dframe.index.map(str.lower)

array(['ny', 'la', 'sf'], dtype=object)

In [104]:
dframe.index = dframe.index.map(str.lower)

In [105]:
dframe

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [106]:
dframe.rename(index = str.title, columns = str.lower)

a  b   c   d
Ny  0  1   2   3
La  4  5   6   7
Sf  8  9  10  11

In [107]:
dframe.rename(index={'ny':'NEW YORK'},
             columns ={'A':'ALPHA'})


ALPHA  B   C   D
NEW YORK      0  1   2   3
la            4  5   6   7
sf            8  9  10  11

In [109]:
dframe.rename(index={'ny':'NEW YORK'},
             columns ={'A':'ALPHA'}, inplace = True)

In [110]:
dframe

ALPHA  B   C   D
NEW YORK      0  1   2   3
la            4  5   6   7
sf            8  9  10  11

# Binning -->lecture 39

In [111]:
years =[1990,1992,1997,2012,2008,2004,1993,1995,2000,2005]

In [112]:
decade_bins = [1960,1970,1980,1990,2000,2010,2020]

In [113]:
decade_cat =pd.cut(years, decade_bins)
# cut years into decade_bins

In [114]:
decade_cat

[(1980, 1990], (1990, 2000], (1990, 2000], (2010, 2020], (2000, 2010], (2000, 2010], (1990, 2000], (1990, 2000], (1990, 2000], (2000, 2010]]
Categories (6, object): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [115]:
pd.value_counts(decade_cat)
# count the values in each bins 

(1990, 2000]    5
(2000, 2010]    3
(2010, 2020]    1
(1980, 1990]    1
(1970, 1980]    0
(1960, 1970]    0
dtype: int64

In [116]:
pd.cut(years, 2, precision=1)
#cut years into 2 bins 

[(1990, 2001], (1990, 2001], (1990, 2001], (2001, 2012], (2001, 2012], (2001, 2012], (1990, 2001], (1990, 2001], (1990, 2001], (2001, 2012]]
Categories (2, object): [(1990, 2001] < (2001, 2012]]

# Outlier --> Lecture 40

In [117]:
np.random.seed(12345)

In [118]:
dframe = DataFrame(np.random.randn(1000,4))
dframe.head()

0         1         2         3
0 -0.204708  0.478943 -0.519439 -0.555730
1  1.965781  1.393406  0.092908  0.281746
2  0.769023  1.246435  1.007189 -1.296221
3  0.274992  0.228913  1.352917  0.886429
4 -2.001637 -0.371843  1.669025 -0.438570

In [119]:
dframe.tail()

0         1         2         3
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

In [120]:
dframe.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [121]:
col = dframe[0]

In [122]:
col.head()

0   -0.204708
1    1.965781
2    0.769023
3    0.274992
4   -2.001637
Name: 0, dtype: float64

In [123]:
col[np.abs(col)> 3 ]

523   -3.428254
900    3.366626
Name: 0, dtype: float64

In [127]:
dframe[(np.abs(dframe)>3).any(1)]
# each row will have one column who has abs. value above 3 

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [128]:
dframe[np.abs(dframe)>3 ] = np.sign(dframe)*3
#turning all values above 3(abs) will became -3 and 3

In [129]:
dframe.describe()
# check the min and max. Capped at -3 and 3.

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

# Permutation --> Lecture 41

In [4]:
dframe = DataFrame(np.arange(16).reshape(4,4))

In [5]:
blender = np.random.permutation(4)
# get random 0,1,2,3

In [6]:
blender

array([0, 3, 2, 1])

In [7]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [8]:
dframe.take(blender)
# this will blend the dframe by changing the index 1,3,0,2(which is the blender)


0   1   2   3
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11
1   4   5   6   7

In [13]:
box = np.array([10,20,30])


In [14]:
shaker=np.random.randint(0, len(box), size=10)
# permutation with replacement 0 to length of the box and size of shaker is 10

In [15]:
shaker
# these are index 

array([1, 2, 2, 1, 2, 0, 2, 0, 2, 0])

In [17]:
hand_grabs = box.take(shaker)
hand_grabs
# these are values 

array([20, 30, 30, 20, 30, 10, 30, 10, 30, 10])

# Groupby --> Lecture 42


In [18]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [21]:
dframe = DataFrame({'k1':['x','x','y','y','z'],
                   'k2':[ 'alpha', 'beta', 'alpha', 'beta','alpha'],
                   'dataset1':np.random.randn(5),
                   'dataset2':np.random.randn(5)})
dframe

dataset1  dataset2 k1     k2
0  1.911655  1.629130  x  alpha
1 -0.932795  0.312263  x   beta
2  0.679235 -0.031522  y  alpha
3  0.061161  1.017694  y   beta
4 -1.231239 -1.863183  z  alpha

In [24]:
group1 = dframe['dataset1'].groupby(dframe['k1'])
group1
# you will not see anything because groupby requires a function 

In [26]:
group1.mean()

k1
x    0.489430
y    0.370198
z   -1.231239
Name: dataset1, dtype: float64

In [29]:
cities = np.array(['NY', 'LA', 'LA', 'NY', 'NY'])
month = np.array(['Jan', 'Feb', 'Jan', 'Feb', 'Jan'])

In [34]:
dframe['dataset1'].groupby([cities, month]).mean()
# grouping by the index posistion and then averaging the value 

LA  Feb   -0.932795
    Jan    0.679235
NY  Feb    0.061161
    Jan    0.340208
Name: dataset1, dtype: float64

In [35]:
dframe.groupby('k1').mean()
#grouping only by one key 

dataset1  dataset2
k1                    
x   0.489430  0.970697
y   0.370198  0.493086
z  -1.231239 -1.863183

In [38]:
dframe.groupby(['k1','k2']).mean()
#grouping by the multiple keys 

dataset1  dataset2
k1 k2                       
x  alpha  1.911655  1.629130
   beta  -0.932795  0.312263
y  alpha  0.679235 -0.031522
   beta   0.061161  1.017694
z  alpha -1.231239 -1.863183

In [39]:
dframe.groupby(['k1']).size()
# check sizes 

k1
x    2
y    2
z    1
dtype: int64

In [43]:
# iterating the groupby 
for name,group in dframe.groupby('k1'):
    print 'this is %s group' %name
    print group
    print '\n'


this is x group
   dataset1  dataset2 k1     k2
0  1.911655  1.629130  x  alpha
1 -0.932795  0.312263  x   beta


this is y group
   dataset1  dataset2 k1     k2
2  0.679235 -0.031522  y  alpha
3  0.061161  1.017694  y   beta


this is z group
   dataset1  dataset2 k1     k2
4 -1.231239 -1.863183  z  alpha


